export const products = [
    {
        id: 1,
        name: "Ring",
        price: 149,
        inStock: true,
        madeIn: "Japan",
        image: "https://s1.apart.pl/products/jewellery/packshot/45919/apart-p-102201--0.jpg",
    },
    {
        id: 2,
        name: "Neckless",
        price: 249,
        inStock: false,
        madeIn: "China",
        image: "https://tse1.mm.bing.net/th?id=OIP.FxdbUxK_7rjyCt9t2-5IiQHaHa&pid=Api&P=0&h=180",
    },
    {
        id: 3,
        name: "Ear Tops",
        price: 459,
        inStock: true,
        madeIn: "Pakistan",
        image: "https://tse4.mm.bing.net/th?id=OIP.SYBcdH4oFLeZGRGNik1G8AHaFj&pid=Api&P=0&h=180",
    },
    {
        id: 4,
        name: "Ear Rings",
        price: 359,
        inStock: true,
        madeIn: "Pakistan",
        image: "https://tse1.mm.bing.net/th?id=OIP._laB0yF2tWtlxEi50U3aIgHaHa&pid=Api&P=0&h=180",
    },
    {
        id: 5,
        name: "Bangles",
        price: 99,
        inStock: false,
        madeIn: "India",
        image: "https://tse2.mm.bing.net/th?id=OIP.AOJeS5wajknRLCeVkxIWQQHaHa&pid=Api&P=0&h=180",
    },
    {
        id: 6,
        name: "Common Pins",
        price: 49,
        inStock: true,
        madeIn: "Germany",
        image: "https://i.pinimg.com/originals/5d/b7/98/5db798589983d676f9138677696e16d7.jpg",
    },
    {
        id: 7,
        name: "Hair Band",
        price: 249,
        inStock: false,
        madeIn: "England",
        image: "https://i5.walmartimages.com/asr/7506035b-0db0-4b35-9643-ac657d3b9ccb_1.f9b5d181b69341d9a4c46f4256040963.jpeg",
    },
    {
        id: 8,
        name: "Pony",
        price: 30,
        inStock: true,
        madeIn: "Pakistan",
        image: "https://www.tjara.com/wp-content/uploads/2020/02/10997921656_1708328313.jpg",
    },
    {
        id: 9,
        name: "Bindya",
        price: 499,
        inStock: true,
        madeIn: "Kenya",
        image: "https://assets0.mirraw.com/images/7027348/image_zoom.jpeg?1557859352",
    },
    {
        id: 10,
        name: "Lip Stick",
        price: 300,
        inStock: false,
        madeIn: "Kenya",
        image: "https://tse3.mm.bing.net/th?id=OIP.QKSU-Q4I9lFGAmAoVkl2nAHaFj&pid=Api&P=0&h=180",
    },
    {
        id: 11,
        name: "Base",
        price: 149,
        inStock: true,
        madeIn: "Saudi Arabia",
        image: "https://s3.amazonaws.com/images.ecwid.com/images/19950002/1460753161.jpg",
    },
]